version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: node -v
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      #- run: sudo npm install -g npm@latest
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run build
      - run: npm test
      - run: |
          name="$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM-debug" && \
          mkdir packed && \
          mv dist/development "$name" && \
          tar zcf "$name.tgz" "$name" && \
          mv "$name.tgz" packed/
      - store_artifacts:
          path: packed
          destination: packed


